http:
  routers:
    apigolang:
      rule: "Host(`api.golang.localdomain`) || Host(`api.golang.hthai.cloud`)"
      entryPoints:
        - web
      service: apigolang

  services:
    apigolang:
      loadBalancer:
        servers:
          # - url: "http://host.docker.internal:8088"  # Replace with your container's IP and port
          - url: "http://golang_api:8088"