@host = http://localhost:8088

GET http://localhost:8088/ping

###
GET http://localhost:8088/documents

###
POST http://localhost:8088/upload HTTP/1.1
Host: localhost
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="title"

Hayden Thai Resume
--WebBoundary
Content-Disposition: form-data; name="file";filename="Hayden Thai_Resume-2.pdf"

< .input/Hayden Thai_Resume-2.pdf

--WebBoundary--

###
GET http://localhost:8088/preview?id=001&token=abc123
###
GET http://localhost:8088/testers
###
POST http://localhost:8088/testers
Content-Type: application/json

{
    "name":"Hello"
}
###
POST http://localhost:8088/register
Content-Type: application/json

{
    "username": "tim5890",
    "password": "password2"    
}

###
POST http://localhost:8088/login
Content-Type: application/json

{
    "username": "tim589",
    "password": "password2"    
}

###
###
POST http://localhost:8088/login
Content-Type: application/json

{
    "username": "tim234",
    "password": "password2"    
}

###


POST http://localhost:8088/users/tim234/changepassword
Content-Type: application/json

{
    "username": "tim234",
    "password": "password2",
    "newpassword": "helasdasda"    
}

###
POST http://localhost:8088/loginjwt
Content-Type: application/json

{
    "username": "tim234",
    "password": "helasdasda12346"    
}

###
POST http://localhost:8088/v1/auth/users/tim5/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njc3NjA2MTgsInR5cGUiOiJyZWZyZXNoIiwidXNlcm5hbWUiOiJ0aW01In0.ZucVaT6ZIrqXaGA-APZ_Kzas15bY4zxqnILTZQ3MCug
Content-Type: application/json

{
    "username": "tim5",
    "password": "hello",
    "newpassword": "hello"    
}

### test auth
GET http://localhost:8088/v1/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjcwNTQwNDcsImlhdCI6MTc2NzA1MDQ0NywidXNlcm5hbWUiOiJ0aW01In0.r9Hq1GbLWd3ECEdIKZ_rfPdpD7bj615MVFmN3mFcSyc


###
POST http://localhost:8088/loginjwt
Content-Type: application/json

{
   "username": "tim5",
    "password": "hello"      
}

###
POST http://localhost:8088/v1/auth/refresh

###
GET http://localhost:8088/v1/auth/me

###
POST http://localhost:8088/v1/auth/users/me
Content-Type: application/json

{
    "tokenId": "ebae29e8-e089-401e-a365-ca52e6309120"
}

###
POST http://localhost:8088/v1/auth/logout

###Test
GET http://localhost:8088/v2/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njc0MjkxMjQsImlhdCI6MTc2NzQyNTUyNCwidG9rZW5JZCI6ImIxMGQyOTMwLTAwMTEtNDM4Ni1iNTk4LWE1YmRkMzRkNzE5NiIsInR5cGUiOiJhY2Nlc3MiLCJ1c2VybmFtZSI6InRpbTUifQ.gHhZNncd6heEaoidVcm0KWthepuZfTqswCPTP3TAG6E

### Test autho upload
POST http://localhost:8088/v1/auth/upload HTTP/1.1
Host: localhost
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="title"

Hayden Thai Resume
--WebBoundary
Content-Disposition: form-data; name="tokenId"

3cf1a029-5525-4610-8a93-0e01d1323bfe
--WebBoundary
Content-Disposition: form-data; name="file";filename="Hayden Thai_Resume-2.pdf"

< .input/Hayden Thai_Resume-2.pdf

--WebBoundary--

###
POST https://api.golang.localdomain/register
Content-Type: application/json

{
    "username": "hthai",
    "password": "hello"    
}

###
POST https://api.golang.localdomain/loginjwt
Content-Type: application/json

{
   "username": "hthai",
    "password": "hello"      
}


###
POST {{host}}/register
Content-Type: application/json

{
    "username": "hthai23",
    "password": "hello"    
}

### 
POST {{host}}/login
Content-Type: application/json

{
    "username": "hthai",
    "password": "hello"    
}
###
GET {{host}}/v1/auth/users/me

Content-Type: application/json

{
    "tokenId": "ab5efec8-00da-4477-87a6-0ecdcd0c96a6"
}

###
GET {{host}}/v1/auth/test

###
POST {{host}}/v1/auth/logout

### Issue with id and username
POST {{host}}/v1/auth/users/hthai2/changepassword
Content-Type: application/json

{
    "username": "hthai2",
    "password": "hello",
    "newpassword": "hello1"    
}

###
POST {{host}}/v1/auth/refresh

###
POST {{host}}/v1/auth/user/changepassword
Content-Type: application/json

{    
    "password": "hello",
    "newpassword": "hello"    
}