version: '3.9'

services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    networks:
      - backend
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic:/etc/traefik/dynamic"

  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your
      MYSQL_DATABASE: your
      MYSQL_USER: your
      MYSQL_PASSWORD: your
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: . # Current directory (where Dockerfile & main.go are)
    container_name: golang_api
    user: "1000:1000"
    ports:
      - "8088:8088"
    volumes:
      - mydata:/app
    environment:
      - GO_ENV=production
      - DB_USER=your
      - DB_PASSWORD=your
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=goDocument
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

volumes:
  mydata:
  dbdata:


networks:
  backend:
    driver: bridge
  traefik:
    external: true
