/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUploadRouteImport } from './routes/_auth.upload'
import { Route as AuthSummaryRouteImport } from './routes/_auth.summary'
import { Route as AuthReportRouteImport } from './routes/_auth.report'
import { Route as AuthEditTableRouteImport } from './routes/_auth.edit-table'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSummaryRoute = AuthSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportRoute = AuthReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEditTableRoute = AuthEditTableRouteImport.update({
  id: '/edit-table',
  path: '/edit-table',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/edit-table': typeof AuthEditTableRoute
  '/report': typeof AuthReportRoute
  '/summary': typeof AuthSummaryRoute
  '/upload': typeof AuthUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/edit-table': typeof AuthEditTableRoute
  '/report': typeof AuthReportRoute
  '/summary': typeof AuthSummaryRoute
  '/upload': typeof AuthUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/signin': typeof SigninRoute
  '/_auth/edit-table': typeof AuthEditTableRoute
  '/_auth/report': typeof AuthReportRoute
  '/_auth/summary': typeof AuthSummaryRoute
  '/_auth/upload': typeof AuthUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/edit-table'
    | '/report'
    | '/summary'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/edit-table' | '/report' | '/summary' | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/signin'
    | '/_auth/edit-table'
    | '/_auth/report'
    | '/_auth/summary'
    | '/_auth/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/summary': {
      id: '/_auth/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthSummaryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/report': {
      id: '/_auth/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthReportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/edit-table': {
      id: '/_auth/edit-table'
      path: '/edit-table'
      fullPath: '/edit-table'
      preLoaderRoute: typeof AuthEditTableRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthEditTableRoute: typeof AuthEditTableRoute
  AuthReportRoute: typeof AuthReportRoute
  AuthSummaryRoute: typeof AuthSummaryRoute
  AuthUploadRoute: typeof AuthUploadRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEditTableRoute: AuthEditTableRoute,
  AuthReportRoute: AuthReportRoute,
  AuthSummaryRoute: AuthSummaryRoute,
  AuthUploadRoute: AuthUploadRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
